
export const ktvData = [
  {
    "id": "277-ktv",
    "name": "277 KTV",
    "main_image_url": "https://nightlifeasia.wiki/images/thumb/0/0c/277-ktv.jpg/100px-277-ktv.jpg",
    "images": ["https://nightlifeasia.wiki/images/thumb/0/0c/277-ktv.jpg/100px-277-ktv.jpg"],
    "address": "277 Geylang Rd",
    "country": "Singapore",
    "phone": "+6511112222",
    "category": "KTV",
    "price": "S$50 (HH)",
    "description": "A popular KTV in the Geylang area, known for its Vietnamese hostesses.",
    "hours": "5PM - 3AM"
  },
  {
    "id": "ace-club",
    "name": "Ace Club",
    "main_image_url": "https://nightlifeasia.wiki/images/thumb/9/92/Club-ace-ktv.jpg/100px-Club-ace-ktv.jpg",
    "images": ["https://nightlifeasia.wiki/images/thumb/9/92/Club-ace-ktv.jpg/100px-Club-ace-ktv.jpg"],
    "address": "48 Foch Rd, Level 2, Singapore 209272",
    "country": "Singapore",
    "phone": "+6511112223",
    "category": "KTV",
    "price": "S$50 (HH)",
    "description": "High-end KTV with a good selection of Vietnamese hostesses.",
    "hours": "3:30PM - 3AM"
  },
  {
    "id": "avatar-ktv",
    "name": "Avatar KTV",
    "main_image_url": "https://nightlifeasia.wiki/images/thumb/4/40/Avatar_ktv_logo1.png/100px-Avatar_ktv_logo1.png",
    "images": ["https://nightlifeasia.wiki/images/thumb/4/40/Avatar_ktv_logo1.png/100px-Avatar_ktv_logo1.png"],
    "address": "35 Selegie Road, #05-26, Parklane Shopping Mall",
    "country": "Singapore",
    "phone": "+6511112224",
    "category": "KTV",
    "price": "S$100 (NH)",
    "description": "A 'hot' KTV with a large selection of Vietnamese ladies.",
    "hours": "4PM - 3AM"
  },
  {
    "id": "azit-korean-ktv",
    "name": "Azit Korean KTV",
    "main_image_url": "https://nightlifeasia.wiki/images/thumb/c/ce/Azit_korean_ktv_logo1.png/100px-Azit_korean_ktv_logo1.png",
    "images": ["https://nightlifeasia.wiki/images/thumb/c/ce/Azit_korean_ktv_logo1.png/100px-Azit_korean_ktv_logo1.png"],
    "address": "5 Coleman Street Excelsior Tower Lobby, Hotel, #05-00 Peninsula Excelsior",
    "country": "Singapore",
    "phone": "+6511112225",
    "category": "KTV",
    "price": "???",
    "description": "A Korean style KTV for those looking for a different experience.",
    "hours": "8PM - 3AM"
  },
  {
    "id": "b12-ktv",
    "name": "B12 KTV",
    "main_image_url": "https://nightlifeasia.wiki/images/thumb/4/4c/B12-Delux-Logo.jpg/100px-B12-Delux-Logo.jpg",
    "images": ["https://nightlifeasia.wiki/images/thumb/4/4c/B12-Delux-Logo.jpg/100px-B12-Delux-Logo.jpg"],
    "address": "#B1-19, Havelock 2, 2 Havelock Rd",
    "country": "Singapore",
    "phone": "+6511112226",
    "category": "KTV",
    "price": "$50 HH",
    "description": "A deluxe KTV experience with modern facilities.",
    "hours": "4:00PM - 3:00AM"
  },
  {
    "id": "catwalk-ktv-singapore",
    "name": "Catwalk KTV (Singapore)",
    "main_image_url": "https://nightlifeasia.wiki/images/thumb/c/cc/Catwalk-ktv2.jpg/100px-Catwalk-ktv2.jpg",
    "images": ["https://nightlifeasia.wiki/images/thumb/c/cc/Catwalk-ktv2.jpg/100px-Catwalk-ktv2.jpg"],
    "address": "200 Jalan Sultan Textile Centre Level 7",
    "country": "Singapore",
    "phone": "+6511112227",
    "category": "KTV",
    "price": "S$70 (HH)",
    "description": "Famous for its 'hot' selection of Vietnamese hostesses.",
    "hours": "4PM - 3AM"
  },
  {
    "id": "club-chanel",
    "name": "Club Chanel",
    "main_image_url": "https://nightlifeasia.wiki/images/thumb/a/ae/Club-chanel.jpg/100px-Club-chanel.jpg",
    "images": ["https://nightlifeasia.wiki/images/thumb/a/ae/Club-chanel.jpg/100px-Club-chanel.jpg"],
    "address": "35 Selegie Road, #B1-09, Parklane Shopping Mall",
    "country": "Singapore",
    "phone": "+6511112228",
    "category": "KTV",
    "price": "S$100",
    "description": "A classic Chinese KTV with a more mature crowd.",
    "hours": "5PM - 3AM"
  },
  {
    "id": "club-diamond",
    "name": "Club Diamond",
    "main_image_url": "https://nightlifeasia.wiki/images/thumb/c/ca/Club_diamond_logo1.jpg/100px-Club_diamond_logo1.jpg",
    "images": ["https://nightlifeasia.wiki/images/thumb/c/ca/Club_diamond_logo1.jpg/100px-Club_diamond_logo1.jpg"],
    "address": "6001 Beach Road, Golden Mile Tower #B1-10",
    "country": "Singapore",
    "phone": "+6511112229",
    "category": "KTV",
    "price": "???",
    "description": "A Thai-style KTV located in Golden Mile Tower.",
    "hours": "7PM - 3AM"
  },
  {
    "id": "club-dream-ktv",
    "name": "Club Dream KTV",
    "main_image_url": "https://nightlifeasia.wiki/images/thumb/f/fb/Club_dream_ktv.jpg/100px-Club_dream_ktv.jpg",
    "images": ["https://nightlifeasia.wiki/images/thumb/f/fb/Club_dream_ktv.jpg/100px-Club_dream_ktv.jpg"],
    "address": "5 Koek Road, #04-29, Cuppage Plaza",
    "country": "Singapore",
    "phone": "+6511112230",
    "category": "KTV",
    "price": "???",
    "description": "A local KTV catering to the Singaporean crowd.",
    "hours": "8PM - 3AM"
  }
]
    